import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Configure soehne Font
const sohne = localFont({
  src: [
    {
      path: '../public/fonts/WOFF2/soehne-buch.woff2', 
      weight: '400',
      style: 'normal',
    },
    {
      path: '../publicpublic/fonts/WOFF2/soehne-kraftig.woff2', 
      weight: '700',
      style: 'normal',
    },
  ],
  variable: "--font-sohne",
});

export const metadata: Metadata = {
  title: "Reform Assessment",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sohne.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}